version: '3.8'
name: oversound
# Definici√≥n de los servicios
services:
  db:
    image: postgres:16
    network_mode: "host"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "12345"
      POSTGRES_DB: postgres
    volumes:
      - db_data:/var/lib/postgresql/data

  fnd:
    image: fnd
    network_mode: "host"
    build:
      context: ./FND
      dockerfile: Dockerfile
    depends_on:
      - syu
      - tya
      - tpp
      - pt
      - rye
      - db
    environment:
      SERVER_IP: 0.0.0.0
      SERVER_PORT: 8000
      HOST_FND: http://localhost:8000
      HOST_SYU: http://localhost:8080
      HOST_TYA: http://localhost:8081
      HOST_TPP: http://localhost:8082
      HOST_PT:  http://localhost:8083
      HOST_RYE: http://localhost:8084
  
  syu:
    image: syu
    network_mode: "host"
    build:
      context: ./SYU
      dockerfile: Dockerfile
    environment:
      SERVER_ADDRESS: 0.0.0.0
      SERVER_PORT: 8080
      TYA_HOST: http://localhost:8081
      DB_HOST: localhost
      DB_PORT: 5432
      DB_PWD: "12345"
      DB_NAME: "syu"
      DB_USER: "syu_admin"
    volumes:
      - syu_data:/syu/src/main/resources/static/pfp

  tya:
    image: tya
    network_mode: "host"
    build:
      context: ./TYA
      dockerfile: Dockerfile
    environment:
      HOST_TYA_IP: +
      HOST_TYA_PORT: 8081
      HOST_SYU: localhost
      DB_HOST: localhost
      DB_PORT: 5432
      DB_PWD: "12345"
      DB_NAME: "tya"
      DB_USER: "tya_admin"
    volumes:
      - tya_data:/tya/static
  
  tpp:
    image: tpp
    network_mode: "host"
    build:
      context: ./TPP
      dockerfile: Dockerfile
    environment:
      HOST: 0.0.0.0
      PORT: 8082
      HOST_SYU: localhost
      HOST_TYA: localhost
      DB_HOST: localhost
      DB_PORT: 5432
      DB_PWD: "12345"
      DB_NAME: "tpp"
      DB_USER: "tpp_admin"
  
  pt:
    image: pt
    network_mode: "host"
    build:
      context: ./PT
      dockerfile: Dockerfile
    environment:
      HOST: 0.0.0.0
      PORT: 8083
      DB_HOST: localhost
      DB_PORT: 5432
      DB_PWD: "12345"
      DB_NAME: "pt"
      DB_USER: "pt_admin"
  
  rye:
    image: rye
    network_mode: "host"
    build:
      context: ./RYE
      dockerfile: Dockerfile
    environment:
      HOST: 0.0.0.0
      PORT: 8084
      DB_HOST: localhost
      DB_PORT: 5432
      DB_PWD: "12345"
      DB_NAME: "rye"
      DB_USER: "rye_admin"

volumes:
  syu_data:
  tya_data:
  db_data: